# Generated by Django 5.2.1 on 2025-05-16 06:54

import core.models.recording
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recording_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recording',
            name='file',
            field=models.FileField(upload_to=core.models.recording.update_filename),
        ),
    ]
